spring:
  application:
    name: adoptie
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  config:
    import: "optional:dotenv:.env"
  main.banner-mode:
    off

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
jwt:
  secret: ${JWT_SECRET}

app:
  upload:
#    dir: ${user.home}/pet-adoption/uploads/imagini
      supabaseUrl: ${SUPABASE_URL}
      supabaseAccessKey: ${ACCESS_KEY_ID}
      supabaseSecretKey: ${SECRET_KEY_ACCESS}
      bucket: ${DIR_NAME}
      region: ${REGION}

model:
  ai:
    path: ./model/model.onnx
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, loggers


